### ISSUE TITLE
Support for nested properties

### ISSUE THREAD

**Issue by micheleriva** [nearform/lyra#14]
**Is your feature request related to a problem? Please describe.**
As for now, Lyra does not support nested properties. Thus, the following code will break:

```js
import { lyra } from '@nearfom/lyra';

const movieDB = new Lyra({
  schema: {
    title: 'string',
    director: 'string',
    plot: 'string',
    year: 'number',
    isFavorite: 'boolean',
    cast: { // <-------- objects are not supported yet
      director: 'string',
      leading: 'string'
    }
  }
});
```

We should grant support for nested properties to Lyra

**Comment by DanieleFedeli** [comment]
Can I pick this up? 
I promise nothing since I never looked the source code but I would like to try it

**Comment by micheleriva** [comment]
Go for it 🙂

**Comment by DanieleFedeli** [comment]
Schema type is not propagated throughout Lyra instance.  Is this a design choice?

**Comment by micheleriva** [comment]
What do you mean by that?

**Comment by DanieleFedeli** [comment]
I mean when I create an instance with a specific schema like that:

```typescript
const db = new Lyra({ schema: { quote: "string",  author: "string" }});
```
		
The insert method does not inherit the type from the schema passed
So If I do:
```typescript
await db.insert({ nonExistingField: "A_RANDOM_STRING"});
```

I will get INVALID_DOC_SCHEMA,
This error is only raised at runtime, but at compile time it is not detected.

**Comment by micheleriva** [comment]
@DanieleFedeli got it, this is a missing feature that I'd definitely love to have!

**Comment by DanieleFedeli** [comment]
I can work on that also, but now I am focusing on this one 😆
