### ISSUE TITLE
Create better docs

### ISSUE THREAD

**Issue by micheleriva** [nearform/lyra#24]
With Lyra's upcoming first stable release, I would love to have a better documentation website, maybe using Docusaurus or something similar. The current design is not very optimal, and documentation is poorly organized

**Comment by thomscoder** [comment]
Sounds good!
I'll follow along.

**Comment by thomscoder** [comment]
> I would go with Docusaurus or something similar 🙂

Hey @micheleriva 👋🏽
I would like to ask you a couple of things ([work in progress](https://github.com/thomscoder/lyra/tree/betterDocs))

<img width="1427" alt="Schermata 2022-07-23 alle 15 13 43" src="https://user-images.githubusercontent.com/78874117/180606631-0041a0ef-6e65-4ec3-b329-82bf3daeac43.png">
<img width="1428" alt="Schermata 2022-07-23 alle 15 13 55" src="https://user-images.githubusercontent.com/78874117/180606638-fed0c47f-90b1-4892-ba26-fc36a9b64a49.png">
<img width="1426" alt="Schermata 2022-07-23 alle 15 09 40" src="https://user-images.githubusercontent.com/78874117/180606427-b569ce25-96ce-47e7-a692-410c7f880cbf.png">


- [ ] Color palette & styling (for starters I based the style on redux and pnpm docs)
- [ ] Search bar
- [ ] Playground (try a demo)


For the search bar I was thinking about integrating DocSearch by Algolia, but it requires configurations from the owner of the repo (API KEY, APP ID etc...). This is why i reached you out before proceeding.

[Docusaurus search bar docs](https://docusaurus.io/docs/search)
https://docsearch.algolia.com/

For the `Playground` thing I thought it was a cool idea to integrate (through an external link or even embedded idk) the react example you wrote ✌🏽

**Comment by micheleriva** [comment]
hey @thomscoder , this looks fantastic!

**Comment by micheleriva** [comment]
For searching, I think we could use something different from Algolia, as stated here: https://docusaurus.io/docs/search#using-local-search

In the future, we'll be using Lyra of course 🙂

**Comment by thomscoder** [comment]
Ehyy, thanks for the reply and the heads up on local-search!

> In the future, we'll be using Lyra of course 🙂
eheh, of course 😉 

<hr>

One last thing I would ask to consider is if integrating in inside the repo or creating a brand new repository to host it , for better mantainability, as the project could potentially grow huge (with translations or other docs sections in the future) 💯👊🏽

**Comment by micheleriva** [comment]
You're right about maintaining large docs, but for now let's keep it under the same repo, so more people can get involved 🙂

**Comment by thomscoder** [comment]
Perfect! 💯  thank you again!

**Comment by thomscoder** [comment]
For future me:
- Importing Lyra in docusaurus requires a bit more configurations.
- Solved by following this Gist: https://gist.github.com/rohit-gohri/59d0e6a9b4f51d1dd39f5e8894050f74

<img width="1423" alt="Schermata 2022-07-27 alle 19 59 35" src="https://user-images.githubusercontent.com/78874117/181364900-e96762e1-0f9a-40e0-aeea-8076cf3a4ec1.png">

<hr>

The react example does not work out of the box. Now I implemented a small Lyra example in the client with a list of 800+ pokemons (from which I extracted only the Id and the English name), the `pokedex` array contains more.

<img width="1427" alt="Schermata 2022-07-27 alle 22 17 48" src="https://user-images.githubusercontent.com/78874117/181365408-1ae17fb0-ec88-46a8-9f48-a1c7b03bbb41.png">

**Comment by micheleriva** [comment]
@thomscoder that's related to #37. We're planning to remove Natural as a dependency as it breaks on browsers 😢 

We'll implement search via Lyra later on 😄

**Comment by thomscoder** [comment]
Holy smokes! how did I miss that lol. my bad. Well it wasn't wasted time since I learned something new about webpack bundling ahah

<hr>

Oh alright. sounds about right. I'll remove the demo component right away.

**Comment by micheleriva** [comment]
Hi @thomscoder !
Any update on the docs? 🙂

**Comment by thomscoder** [comment]
Heyy, working on it!
My plan was to open a PR this weekend!
sorry for the delay

**Comment by micheleriva** [comment]
No problem at all!

**Comment by micheleriva** [comment]
Closing this, PR merged
