### ISSUE TITLE
Search method returns undefined elements

### ISSUE THREAD

**Issue by mateonunez** [nearform/lyra#29]
**Describe the bug**
Searching by a term that doesn't exist, Lyra returns `X` undefined elements.

The error also occurs using `limit`, `property` or `exact` params.

**To Reproduce**
1. `lyra.search({ term: "whatever" })`

**Expected behavior**
Lyra shouldn't return `X` undefined elements. Instead of that should return an empty array.

**Screenshots**

![image](https://user-images.githubusercontent.com/11861080/179612379-4981aff4-2baa-4101-84e7-d1946299a290.png)

**Desktop:**

- OS: Windows 11
- Environment: Node
- Node: v18.6.0
- pnpm: v7.5.1
- Lyra: v0.0.1-beta-12

**Comment by micheleriva** [comment]
When retrieving data, we create an array of `x` length, where `x` is the `limit` search param. That way we avoid unnecessary dynamic allocations when adding data to the `results` array, but of course is causing this problem

```js
    const results: RetrievedDoc<TSchema>[] = Array.from({
      length: limit,
    });
``` 

Thanks for opening the issue!

**Comment by mateonunez** [comment]
And what would be the correct way to fix it? Create an Array that also allows dynamic allocations? Or filter the Array before the return?

**Comment by micheleriva** [comment]
I'd say... let's benchmark these operations with different array sizes. Let's see when is convenient filtering vs dynamic arrays given the docs we have
