### ISSUE TITLE
Missing .tsv file in benchmarks

### ISSUE THREAD

**Issue by thomscoder** [nearform/lyra#44]
**Describe the bug**
Hoping I'm not missing some configurations... benchmarks are crashing at
 
```js
const fileStream = fs.createReadStream("./dataset/title.tsv");
```

**To Reproduce**
1. Running `pnpm benchmark` from root directory (supposing no external/manual confurations are needed 👀) 

**Screenshots**
<img width="678" alt="Schermata 2022-07-24 alle 00 05 33" src="https://user-images.githubusercontent.com/78874117/180624665-8d0b380d-a654-4e15-b1d7-5cd097c463f9.png">

**Desktop (please complete the following information):**
 - OS: MacOS M1 Monterey 12.4
 - Node: 18.6.0

**Comment by micheleriva** [comment]
Hey @thomscoder, you can download that file by running the `get-imdb-dataset.sh` script in `/packages/benchmarks` 🙂
