### ISSUE TITLE
Duplicate results when the term matches multiple fields

### ISSUE THREAD

**Issue by lucaong** [nearform/lyra#48]
**Describe the bug**
 
On Lyra `0.0.1-beta-14` when a search term matches multiple fields, the results contain duplicates.

**To Reproduce**

Here's a reproduction test:

```javascript
it("Should return unique results, even if the term matches multiple fields", async () => {
  const db = new Lyra({
    schema: {
      title: "string",
      text: "string",
    }
  });

  await db.insert({
    title: "something",
    text: "something",
  });

  const results = await db.search({ term: "something" });

  // The following assertion fails:
  // Expected: 1
  // Received: 2
  expect(results.count).toEqual(1);
});
```

**Expected behavior**

Results should always be unique, even if the search term matches multiple fields.

**Comment by thomscoder** [comment]
expanding on this:
<img width="747" alt="Schermata 2022-07-26 alle 23 00 52" src="https://user-images.githubusercontent.com/78874117/181111195-aca95ce1-b8b5-489f-ac48-92bf79c89959.png">

**Comment by micheleriva** [comment]
Thank you @lucaong so much for opening this issue. It has been fixed with https://github.com/nearform/lyra/commit/f8138656fdc530173b02b36be23f41eb3acac10d!
