### ISSUE TITLE
Search case-sensitive for terms with a length less than 3

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [nearform/lyra#58]
**Describe the bug**
It seems that the search is case-sensitive for words with a length < 3

**To Reproduce**
Insert records like: 
* ```if you are interested```
* ```if you will go out..```
* search for the term `If`
* you retrieve 0 result
* if you search for the terms: `if you`
* you get results

**Expected behavior**
I am expecting that the search is case-sensitive or not with a specific rule

related PR: #57 (but it doesn't fix the problem)

**Comment by micheleriva** [comment]
@AlessandroMinoccheri my question is... do we want case-sensitive searches at all?

**Comment by AlessandroMinoccheri** [comment]
This is the main question @micheleriva 
We can have a default behavior and a parameter to specify if the search is case-sensitive or not IMHO.
But we need to have a default and consistent behavior in the code. 
This PR could be useful to understand it not only to solve the problem.

**Comment by AlessandroMinoccheri** [comment]
If I understood well the biggest problem is that with two characters we have a behavior with more another behavior.

**Comment by micheleriva** [comment]
Adding support for case-sensitive matches may lead us to extra effort with minimal benefits... with the latest PR I merged, we are converting all the tokens to lowercase so the problem should be resolved (in fact, I had to edit a couple of tests that were wrong for the reason you're suggesting).

If we can find a way to add case-sensitive matches with minimum efforts, I'm ok with that!

**Comment by AlessandroMinoccheri** [comment]
I tried the behavior and it seems to work fine.
Can we explicitly write that the search is case-insensitive? Or is already written?

**Comment by micheleriva** [comment]
I was waiting for #24 to be completed before updating the overall documentation!

**Comment by AlessandroMinoccheri** [comment]
Ok, so I can close this issue!
Thank you :)
