### ISSUE TITLE
example page not working

### ISSUE THREAD

**Issue by danielehrhardt** [nearform/lyra#64]
example link not working:
https://nearform.github.io/lyra/guide/

https://nearform.github.io/packages/examples -➤ 404

**Comment by micheleriva** [comment]
Hi @danielehrhardt, we're working on the docs, we'll update you asap

**Comment by micheleriva** [comment]
Work in progress #65

**Comment by danielehrhardt** [comment]
Some example would be nice. I cannot find one currently in the new Docs.

**Comment by micheleriva** [comment]
@danielehrhardt here it is: https://nearform.github.io/lyra/demo

**Comment by danielehrhardt** [comment]
Awesome thanks!
