### ISSUE TITLE
Extend Lyra with basic embedding based search?

### ISSUE THREAD

**Issue by creatorrr** [nearform/lyra#69]
If it makes sense, then it might be possible to do this efficiently with tensorflow-js and an optimised encoder model

**Comment by micheleriva** [comment]
Hi @creatorrr ,
we're planning to add support for a plug-in system to Lyra, so it might be possible to do that in the near future!

**Comment by creatorrr** [comment]
Closing this for now. Perhaps we can revisit this after plugin system is shipped!
