### ISSUE TITLE
[feat] persist/restore database

### ISSUE THREAD

**Issue by gioboa** [nearform/lyra#70]
**Is your feature request related to a problem? Please describe.**
In order to be in line with cloud environment (or instance rebooting) an API for persist/restore in memory database could be fantastic.

**Describe the solution you'd like**
I'd like file system usage for this kind of activities because you can resize disks size without reboot the instance and disk usage is cheaper than ram.

**Comment by micheleriva** [comment]
Hi @gioboa!
We've already implemented this feature 🙂 we can serialize the entire index and write it to disk for the reason you mentioned. We're currently trying to implement a common API for Node.js, Bun, and Deno, as disk access may vary.

We'll be releasing this feature with the first stable release or so

**Comment by gioboa** [comment]
Nice 👏 I'm looking forward to try this feature 👍

**Comment by simonireilly** [comment]
Super interested in the solution taken.

I was serializing the tree to a JSON representation, with a separate file for the doc map. Seeding from a file of just schema documents was very slow for cold starts on edge nodes

**Comment by micheleriva** [comment]
@simonireilly we made a full rewrite of our APIs and data structures right before the first initial release. You can now serialize the whole index using protocol buffers, dpack, json, whatever you prefer, we made it fully compatible with most modern serialization formats 🙂  That means that you could also run this in the browser (cc @matthewp )

**Comment by micheleriva** [comment]
@matthewp, @gioboa, a little update: this is a work in progress in the https://github.com/LyraSearch/plugin-disk-persistence repo. Any help would be highly appreciated 🙏

**Comment by micheleriva** [comment]
I'm gonna close this issue and pin it as it might be interesting for other people wondering how to persist Lyra data

**Comment by matthewp** [comment]
This sounds great, thanks a lot!

**Comment by matthewp** [comment]
From an API perspective, if I was creating a persistence package, I would want the ability to persist on each change to the database. It might be nice if a lyra DB was an event emitter for that reason. I could imagine a disk persistence package working like:

```js
const persist = (db, format) => {
  saveToDisk(db, format);

  db.addEventListener('change', () => {
    saveToDisk(db, format);
  });
};
```

That way a user would only need to call `persist` once and not manage calling it every time they inserted, removed, etc.

**Comment by micheleriva** [comment]
@matthewp let's discuss this in the disk persistence repo 🙂
