### ISSUE TITLE
React example can't find built Lyra package

### ISSUE THREAD

**Issue by mateonunez** [nearform/lyra#71]
**Describe the bug**

With a fresh clone of Lyra, try to run the `example/with-react` package and I've got the following error:

![image](https://user-images.githubusercontent.com/11861080/182116125-be062629-b602-4abf-9ad9-5f10b4463ef6.png)

**To Reproduce**
1. git clone https://github.com/nearform/lyra
2. cd lyra && `npm|yarn|pnpm` install
3. cd pacakges/examples/with-react
4. `npm|yarn|pnpm` dev

**Additional context**

This issue could be fixed by building **Lyra** local package before `build` or `serve` the example.

**Comment by thomscoder** [comment]
Ehyy @mateonunez 👋🏽 
I can work on it!

I was thinking of putting a react example in the docs separately as well (iirc @micheleriva wanted to wait a bit for that 😄 )

**Comment by mateonunez** [comment]
Hi @thomscoder, currently I'm trying to improve the example with React and I'm creating other examples with other frameworks. I think the fix of this issue will be included in the next PRs. But thank you so much for your support! 🙏
