### ISSUE TITLE
Diacritics support

### ISSUE THREAD

**Issue by sandstrom** [nearform/lyra#75]
The search library Sifter (https://github.com/brianreavis/sifter.js/) has support for diacritics. Maybe Lyra could add something similar?

Their implementation is here: https://github.com/brianreavis/sifter.js/blob/master/lib/sifter.js#L444

**Comment by micheleriva** [comment]
That sounds super interesting. Yes, we might be interested in supporting this!

**Comment by sandstrom** [comment]
Nice! 🎉
