### ISSUE TITLE
TypeError when trying to run simple Node project with Lyra imported

### ISSUE THREAD

**Issue by Assassinduck** [nearform/lyra#99]
**Describe the bug**
Get "TypeError: Cannot read properties of undefined (reading 'length')" when trying to run a barebones Node project with Lyra imported

**To Reproduce**
1. Make a Node project and import Lyra.
2. Make a simple Lyra DB and add some items to it.
3. Set up a variable containing a search result from the DB.
4. console.log out the search result.
5. Try to run the file by typing node *FileName*.
6. See an error in the console.

**Expected behavior**
I expected the console log to run smoothly and print out the object that the Search function returns.

**Screenshots**
The example code I tried to run when I got the error.
![bug](https://user-images.githubusercontent.com/24327252/185796467-e1468549-1149-4c1c-9564-6a6afd992bef.png)

The error in the terminal.
![bugterminal](https://user-images.githubusercontent.com/24327252/185796465-6e1fd222-23df-4148-828f-7ef209ac99f0.png)

**Desktop**
 - OS: Windows 10
 - Browser: Brave
 - Version: 1.42.97

**Additional context**
This bug shows up in Lyra 0.0.5. I don't know if it shows up in earlier versions.

**Comment by mateonunez** [comment]
Hi @Assassinduck! 

I think you should change the parameter of `search` method.

```js
const searchResult = search(animeDB, {
  term: "Mob Psyco",
});
```

You should use **term** instead **seriesName**.

**Comment by Assassinduck** [comment]
Thank you!
